# Generated by Django 4.2.7 on 2024-04-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_client_client_name'),
        ('commercialOffer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmed_commercialoffer',
            name='commercialOffer',
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='confirmed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.currency'),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='delivery_time_interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='delivery_time_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.timeunit'),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.destination'),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='duration_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='local_contact',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.payment'),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.shipping'),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.transport'),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='confirmed_commercialoffer',
            name='client_nbr',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='commercialoffer',
            table='commercialOffer',
        ),
        migrations.AlterModelTable(
            name='confirmed_commercialoffer',
            table='confirmed_commercialOffer',
        ),
    ]
