# Generated by Django 5.0.6 on 2024-06-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialoffer',
            options={'ordering': ['-created_at', '-rank']},
        ),
        migrations.AlterModelOptions(
            name='confirmed_commercialoffer',
            options={'ordering': ['-created_at', '-rank']},
        ),
        migrations.AlterModelTable(
            name='commercialoffer',
            table='commercialoffer',
        ),
        migrations.AlterModelTable(
            name='confirmed_commercialoffer',
            table='confirmed_commercialoffer',
        ),
    ]
