# Generated by Django 4.2.7 on 2023-11-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialoffer',
            old_name='valid_date',
            new_name='payment_date',
        ),
    ]
