# Generated by Django 4.2.7 on 2024-04-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0002_remove_confirmed_commercialoffer_commercialoffer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialoffer',
            old_name='delivery_time_interval',
            new_name='delivery_time',
        ),
        migrations.RenameField(
            model_name='confirmed_commercialoffer',
            old_name='delivery_time_interval',
            new_name='delivery_time',
        ),
    ]
