# Generated by Django 4.2.7 on 2023-11-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0002_rename_valid_date_commercialoffer_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialoffer',
            name='client_nbr',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
