# Generated by Django 4.2.7 on 2023-11-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0003_commercialoffer_client_nbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='client_nbr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
