# Generated by Django 4.2.7 on 2023-11-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0004_alter_commercialoffer_client_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='client_nbr',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='offer_nbr',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmed_commercialoffer',
            name='client_nbr',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmed_commercialoffer',
            name='confirmation_nbr',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
