# Generated by Django 4.2.7 on 2024-04-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0004_alter_commercialoffer_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='client_nbr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='confirmed_commercialoffer',
            name='client_nbr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
