# Generated by Django 4.2.7 on 2024-04-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0005_alter_commercialoffer_client_nbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='offer_nbr',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmed_commercialoffer',
            name='confirmation_nbr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
