# Generated by Django 4.2.7 on 2023-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0005_alter_commercialoffer_client_nbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
