# Generated by Django 4.2.7 on 2024-04-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0006_alter_commercialoffer_offer_nbr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialoffer',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='confirmed_commercialoffer',
            name='margin',
        ),
    ]
