# Generated by Django 4.2.7 on 2024-04-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0007_remove_commercialoffer_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialoffer',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_commercialoffer',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
