# Generated by Django 4.2.7 on 2023-12-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_payment_nbr_days'),
        ('commercialOffer', '0008_alter_confirmed_commercialoffer_client_nbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='transport_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
