# Generated by Django 4.2.7 on 2024-04-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0008_commercialoffer_rank_confirmed_commercialoffer_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialoffer',
            options={'ordering': ['-offer_nbr']},
        ),
        migrations.AlterModelOptions(
            name='confirmed_commercialoffer',
            options={'ordering': ['-confirmation_nbr']},
        ),
    ]
