# Generated by Django 4.2.7 on 2024-04-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0009_alter_commercialoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmed_commercialoffer',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
