# Generated by Django 4.2.7 on 2023-12-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_payment_nbr_days'),
        ('commercialOffer', '0009_alter_commercialoffer_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.currency'),
        ),
    ]
