# Generated by Django 4.2.7 on 2023-12-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_payment_nbr_days'),
        ('commercialOffer', '0010_alter_commercialoffer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
