# Generated by Django 4.1.7 on 2023-04-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_nbr', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('phone_number1', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(blank=True, max_length=20)),
                ('email1', models.EmailField(max_length=254, unique=True)),
                ('email2', models.EmailField(blank=True, max_length=254, unique=True)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('internal_contact', models.CharField(blank=True, max_length=200)),
                ('external_contact', models.CharField(blank=True, max_length=200)),
                ('representative', models.CharField(blank=True, max_length=200)),
                ('representative_1', models.CharField(blank=True, max_length=200)),
                ('representative_2', models.CharField(blank=True, max_length=200)),
                ('credit_limit', models.FloatField(blank=True)),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.language')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
