# Generated by Django 4.1.7 on 2023-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_nbr',
            field=models.CharField(max_length=50),
        ),
    ]
