# Generated by Django 4.1.7 on 2023-03-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_table_alter_country_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email1',
            field=models.EmailField(max_length=254),
        ),
    ]
