# Generated by Django 4.1.7 on 2023-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_client_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_nbr',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
