# Generated by Django 4.1.7 on 2023-04-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_country_name_country_country_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_code',
            field=models.CharField(default='eng', max_length=4),
            preserve_default=False,
        ),
    ]
