# Generated by Django 4.1.7 on 2023-05-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_language_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='external_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='internal_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='client.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='representative',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='representative_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='representative_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
