# Generated by Django 4.2.7 on 2023-11-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.representative'),
        ),
    ]
