# Generated by Django 4.1.7 on 2023-06-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=50)),
                ('article_nbr', models.CharField(max_length=20)),
                ('description_de', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customs_tariff', models.CharField(max_length=150)),
                ('customs_description', models.TextField(blank=True, max_length=500)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'article_unit',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_nbr', models.CharField(max_length=20, unique=True)),
                ('client_ref', models.CharField(max_length=50)),
                ('our_ref', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True, max_length=500)),
                ('to_do', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(related_name='projects', to='project.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='TimeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'time_unit',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('supplier_representative', models.CharField(blank=True, max_length=100)),
                ('delivery_type', models.CharField(blank=True, max_length=100)),
                ('internal_representative', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.language')),
            ],
            options={
                'db_table': 'supplier',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_nbr', models.CharField(blank=True, max_length=20, unique=True)),
                ('articles', models.ManyToManyField(to='project.article')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.supplier')),
            ],
            options={
                'db_table': 'quoteRequest',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_nbr', models.CharField(max_length=20)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('delivery_time_interval', models.CharField(max_length=20)),
                ('duration_in_days', models.IntegerField()),
                ('validity_date', models.DateField()),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('articles', models.ManyToManyField(to='project.article')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.currency')),
                ('delivery_time_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.timeunit')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.destination')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.shipping')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.transport')),
            ],
            options={
                'db_table': 'commercial_offer',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.articleunit'),
        ),
    ]
