# Generated by Django 4.1.7 on 2023-03-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_nbr', models.CharField(max_length=50, unique=True)),
                ('client_ref', models.CharField(max_length=255)),
                ('our_ref', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('to_do', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
