# Generated by Django 4.1.7 on 2023-07-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_nbr', models.CharField(max_length=30, unique=True)),
                ('description_de', models.TextField(max_length=1500, null=True)),
                ('description_fr', models.TextField(max_length=1500, null=True)),
                ('description_en', models.TextField(max_length=1500, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customs_tariff', models.CharField(blank=True, max_length=150, null=True)),
                ('customs_description', models.TextField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'article_unit',
            },
        ),
        migrations.CreateModel(
            name='Client_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'client_contact',
            },
        ),
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_nbr', models.CharField(max_length=20, unique=True)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('local_contact', models.BooleanField(default=1)),
                ('delivery_time_interval', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_in_days', models.IntegerField(blank=True, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.currency')),
            ],
            options={
                'db_table': 'commercial_offer',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_nbr', models.CharField(max_length=30, unique=True)),
                ('project_name', models.CharField(max_length=150, null=True)),
                ('our_ref', models.CharField(max_length=50, null=True)),
                ('client_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('project_description', models.TextField(blank=True, max_length=500, null=True)),
                ('to_do', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('client_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.client_contact')),
                ('local_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.local_contact')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_nbr', models.CharField(max_length=30, null=True)),
                ('supplier_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('fax', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=150, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.language')),
            ],
            options={
                'db_table': 'supplier',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TimeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'time_unit',
            },
        ),
        migrations.CreateModel(
            name='Supplier_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.supplier')),
            ],
            options={
                'db_table': 'supplier_contact',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_nbr', models.CharField(max_length=20, unique=True)),
                ('articles', models.ManyToManyField(to='project.article')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.supplier')),
            ],
            options={
                'db_table': 'quoteRequest',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.article')),
                ('commercialOffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.commercialoffer')),
                ('quoteRequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.quoterequest')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='delivery_time_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.timeunit'),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.destination'),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.payment'),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project'),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.shipping'),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.transport'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.articleunit'),
        ),
        migrations.AddField(
            model_name='article',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project'),
        ),
    ]
