# Generated by Django 4.1.7 on 2023-05-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    operations = [
        migrations.AddField(
            model_name='commercialoffer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='client.currency'),
            preserve_default=False,
        ),
    ]
