# Generated by Django 4.1.7 on 2023-04-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_nbr',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_nbr',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='request_nbr',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
