# Generated by Django 4.1.7 on 2023-06-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='margin',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
