# Generated by Django 4.1.7 on 2023-07-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='commercialoffer',
            name='articles',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.article')),
            ],
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='orders',
            field=models.ManyToManyField(to='project.order'),
        ),
    ]
