# Generated by Django 4.2.7 on 2024-03-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
