# Generated by Django 4.2.7 on 2024-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(max_length=4),
        ),
    ]
