# Generated by Django 4.2.7 on 2023-11-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='confirmed_commercialoffer',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
