# Generated by Django 4.1.7 on 2023-03-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
