# Generated by Django 4.1.7 on 2023-08-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_confirmorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmOrder',
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='confirmed',
            field=models.BooleanField(default=0),
        ),
    ]
