# Generated by Django 4.1.7 on 2023-07-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_article_description_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description_de',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_fr',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
