# Generated by Django 4.1.7 on 2023-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_nbr',
            field=models.CharField(default='tst', max_length=50),
            preserve_default=False,
        ),
    ]
