# Generated by Django 4.1.7 on 2023-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_commercialoffer_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='margin',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
