# Generated by Django 4.1.7 on 2023-04-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_article_article_nbr_alter_project_project_nbr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='our_ref',
        ),
    ]
