# Generated by Django 4.1.7 on 2023-05-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_article_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
