# Generated by Django 4.1.7 on 2023-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_article_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
