# Generated by Django 4.1.7 on 2023-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_supplier_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='customs_description',
            field=models.TextField(blank=True),
        ),
    ]
