# Generated by Django 4.1.7 on 2023-05-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_supplier_postal_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timeunit',
            table='time_unit',
        ),
    ]
