# Generated by Django 4.2.7 on 2023-11-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_country_abbreviation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_contact',
            new_name='Buyer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='project',
            name='local_contact',
        ),
        migrations.AddField(
            model_name='project',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.representative'),
        ),
        migrations.DeleteModel(
            name='Local_contact',
        ),
    ]
