# Generated by Django 4.1.7 on 2023-07-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_order_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialoffer',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='commercialOffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.commercialoffer'),
        ),
        migrations.AddField(
            model_name='order',
            name='quoteRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.quoterequest'),
        ),
    ]
