# Generated by Django 4.2.7 on 2023-11-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_confirmed_commercialoffer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliercommand',
            old_name='validity_date',
            new_name='payment_date',
        ),
    ]
