# Generated by Django 5.0.6 on 2024-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_buyer_email_alter_buyer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_contact',
            name='gender',
            field=models.BooleanField(default=1),
        ),
    ]
