# Generated by Django 4.1.7 on 2023-07-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('project', '0003_alter_article_description_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.currency'),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='delivery_time_interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='delivery_time_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.timeunit'),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.destination'),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='duration_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.payment'),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.shipping'),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.transport'),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
