# Generated by Django 4.2.7 on 2024-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_country_country_name_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
