# Generated by Django 4.2.7 on 2024-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
