# Generated by Django 4.2.7 on 2023-11-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_client_contact_buyer_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyer',
            table='buyer',
        ),
    ]
