# Generated by Django 4.1.7 on 2023-08-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('project', '0004_alter_commercialoffer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='articles',
        ),
        migrations.CreateModel(
            name='SupplierCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_nbr', models.CharField(max_length=20, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('delivery_time_interval', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packaging', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_time_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.timeunit')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.payment')),
            ],
        ),
    ]
