# Generated by Django 4.1.7 on 2023-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_commercialoffer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='offer_nbr',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='transport_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
