# Generated by Django 4.1.7 on 2023-04-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_country_name_country_country_name_en_and_more'),
        ('project', '0004_project_our_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.language'),
        ),
    ]
