# Generated by Django 4.2.7 on 2023-11-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_validity_date_suppliercommand_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_nbr', models.CharField(max_length=20, unique=True)),
                ('client_nbr', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('commercialOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.commercialoffer')),
            ],
        ),
    ]
