# Generated by Django 4.1.7 on 2023-07-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_commercialoffer_orders_order_commercialoffer_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
