# Generated by Django 4.1.7 on 2023-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_commercialoffer_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_nbr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
