# Generated by Django 4.2.7 on 2023-11-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_buyer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_contact',
            new_name='buyer',
        ),
    ]
