# Generated by Django 4.1.7 on 2023-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_supplier_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='articles',
            field=models.ManyToManyField(related_name='projects', to='project.article'),
        ),
    ]
