# Generated by Django 4.1.7 on 2023-07-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commercialOffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.commercialoffer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quoteRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.quoterequest'),
        ),
    ]
