# Generated by Django 4.2.7 on 2023-11-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmed_commercialoffer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='suppliercommand',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='confirmed_commercialoffer',
            table='confirmed_commercial_offer',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='suppliercommand',
            table='supplier_command',
        ),
    ]
