# Generated by Django 4.1.7 on 2023-04-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_article_project_project_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='quoteRequest',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.article'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.supplier'),
        ),
    ]
