# Generated by Django 4.1.7 on 2023-07-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_article_table_alter_articleunit_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
