# Generated by Django 4.2.7 on 2023-11-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_confirmed_commercialoffer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='customs_tariff',
            new_name='hs_code',
        ),
    ]
