# Generated by Django 4.1.7 on 2023-08-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_delivery_cost_suppliercommand_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercommand',
            name='delivery_fee',
        ),
    ]
