# Generated by Django 4.1.7 on 2023-04-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_article_quoterequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='article',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='articles',
            field=models.ManyToManyField(to='project.article'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.supplier'),
            preserve_default=False,
        ),
    ]
