# Generated by Django 4.2.7 on 2023-12-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_nbr', models.CharField(max_length=40, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.supplier')),
            ],
            options={
                'db_table': 'quote_request',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_nbr', models.CharField(max_length=40, unique=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('delivery_time_interval', models.CharField(blank=True, max_length=20, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.currency')),
                ('delivery_time_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.timeunit')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.payment')),
                ('quoteRequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quoteRequest.quoterequest')),
            ],
            options={
                'db_table': 'supplier_command',
                'ordering': ['-id'],
            },
        ),
    ]
