# Generated by Django 5.0.6 on 2024-05-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('request_nbr', models.CharField(max_length=100, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.supplier')),
            ],
            options={
                'db_table': 'quote_request',
                'ordering': ['-request_nbr'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('command_nbr', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.currency')),
                ('delivery_time_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.timeunit')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.supplier')),
            ],
            options={
                'db_table': 'supplier_command',
                'ordering': ['-command_nbr'],
            },
        ),
    ]
