# Generated by Django 4.2.7 on 2024-04-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='request_nbr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
