# Generated by Django 5.0.6 on 2024-06-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at', '-rank']},
        ),
        migrations.AlterModelOptions(
            name='suppliercommand',
            options={'ordering': ['-created_at', '-rank']},
        ),
    ]
