# Generated by Django 4.2.7 on 2023-11-30 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='request_nbr',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliercommand',
            name='command_nbr',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliercommand',
            name='quoteRequest',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='quoteRequest.quoterequest'),
            preserve_default=False,
        ),
    ]
