# Generated by Django 4.2.7 on 2024-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0002_alter_quoterequest_request_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercommand',
            name='command_nbr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
