# Generated by Django 4.2.7 on 2024-04-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0003_alter_suppliercommand_command_nbr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-request_nbr']},
        ),
        migrations.AlterModelOptions(
            name='suppliercommand',
            options={'ordering': ['-command_nbr']},
        ),
        migrations.RemoveField(
            model_name='suppliercommand',
            name='quoteRequest',
        ),
    ]
