# Generated by Django 4.2.7 on 2024-04-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_client_client_name'),
        ('quoteRequest', '0004_alter_quoterequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercommand',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercommand',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.supplier'),
            preserve_default=False,
        ),
    ]
