# Generated by Django 4.2.7 on 2024-04-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0005_suppliercommand_project_suppliercommand_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercommand',
            name='delivery_time_interval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
