# Generated by Django 4.2.7 on 2024-04-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0006_alter_suppliercommand_delivery_time_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliercommand',
            old_name='delivery_time_interval',
            new_name='delivery_time',
        ),
    ]
