# Generated by Django 4.2.7 on 2024-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0007_rename_delivery_time_interval_suppliercommand_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercommand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercommand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
