# Generated by Django 4.2.7 on 2024-04-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0008_quoterequest_created_at_quoterequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercommand',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
