# Generated by Django 4.2.7 on 2024-04-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteRequest', '0009_quoterequest_rank_suppliercommand_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliercommand',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
