# Generated by Django 4.2.7 on 2024-03-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0002_alter_commercialoffer_currency_and_more'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='confirmed_commercialOffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='commercialOffer.confirmed_commercialoffer'),
        ),
    ]
