# Generated by Django 4.2.7 on 2023-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_nbr',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
