# Generated by Django 5.0.6 on 2024-06-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at', '-rank']},
        ),
    ]
