# Generated by Django 4.2.7 on 2023-12-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0005_alter_commercialoffer_client_nbr_and_more'),
        ('invoice', '0002_alter_invoice_invoice_nbr'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='invoice',
            name='confirmed_commercialOffer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='commercialOffer.confirmed_commercialoffer'),
            preserve_default=False,
        ),
    ]
