# Generated by Django 4.2.7 on 2024-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_confirmed_commercialoffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_nbr',
            field=models.CharField(max_length=100),
        ),
    ]
