# Generated by Django 4.2.7 on 2023-12-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_invoice_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_nbr',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_nbr',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
