# Generated by Django 4.2.7 on 2023-12-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_client_nbr'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='invoice',
            name='client_nbr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
