# Generated by Django 4.2.7 on 2023-12-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_remove_invoice_commercialoffer'),
    ]

    operations = [
       
    ]
