# Generated by Django 4.2.7 on 2023-12-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_remove_invoice_commercialoffer'),
    ]

    operations = [
      
    ]
