# Generated by Django 4.2.7 on 2023-12-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_remove_invoice_commercialoffer'),
    ]

    operations = [
      
    ]
