# Generated by Django 4.2.7 on 2023-12-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_remove_invoice_commercialoffer'),
    ]

    operations = [
       
    ]
