# Generated by Django 4.2.7 on 2024-04-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialOffer', '0001_initial'),
        ('quoteRequest', '0004_alter_quoterequest_options_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_commercialOffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialOffer.confirmed_commercialoffer'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_quoteRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quoteRequest.suppliercommand'),
        ),
    ]
