# Generated by Django 4.2.7 on 2024-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleunit',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
