# Generated by Django 5.0.6 on 2024-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='article_images/'),
        ),
    ]
