# Generated by Django 4.2.7 on 2024-04-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_confirmed_commercialoffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
