# Generated by Django 4.2.7 on 2024-03-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_articleunit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
