# Generated by Django 4.2.7 on 2024-03-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_client_country_alter_client_language_and_more'),
        ('order', '0003_alter_article_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.articleunit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
