# Generated by Django 4.2.7 on 2024-05-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_confirmed_commercialoffer_and_more'),
        ('order', '0003_alter_order_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
