# Generated by Django 4.2.7 on 2023-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_margin_alter_order_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
