# Generated by Django 4.2.7 on 2023-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_article_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_fr',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
